<a href="https://colab.research.google.com/github/Kabileshwarankabil/numpy-basics/blob/main/numpy_basics01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY** (Numerical Python)
NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])# two dimensional array
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Why use NumPy?
Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

## Most NumPy arrays have some restrictions. For instance:

-  All elements of the array must be of the same type of data.
-  Once created, the total size of the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

In [4]:
arr=np.array([2,4,6,8,10,12,14])
print(arr)
# print each elements of the array with it's index
for i in range(len(arr)):
    print(f'{arr[i]} is at index {i}')


[ 2  4  6  8 10 12 14]
2 is at index 0
4 is at index 1
6 is at index 2
8 is at index 3
10 is at index 4
12 is at index 5
14 is at index 6


In [6]:
print(arr[1:]) # starts from index 1

[ 4  6  8 10 12 14]


In [7]:
print(arr[:5]) # print from beginning index 0 to index 5(exclude 5)

[ 2  4  6  8 10]


**NOTE**
As with built-in Python sequences, NumPy arrays are “0-indexed”: the first element of the array is accessed using index 0, not 1.

In NumPy, a dimension of an array is sometimes referred to as an “axis”. This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. For instance, the array a could represent three points, each lying within a four-dimensional space, but a has only two “axes”.

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element 8 is in row 1 and column 3:

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

# print the element in row 2 and column 4
print(f'{a[1,3]} is in row : 2 , column : 4')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8 is in row : 2 , column : 4


It is familiar practice in mathematics to refer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second to last. This generalizes to arrays with any number of dimensions.

# Array attributes

The number of dimensions of an array is contained in the ndim attribute.

In [12]:
a.ndim

2

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [14]:
a.shape

(3, 4)

In [16]:
print(len(a.shape)==a.ndim)

True


The fixed, total number of elements in array is contained in the size attribute.

In [18]:
print(f'The Size of the array : {a.size}')
import math
print(a.size==math.prod(a.shape))

The Size of the array : 12
True


Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [19]:
print(a.dtype)

int64
